# name: Super-Linter

# on: push

# jobs:
#   super-lint:
#     name: Lint code base
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Run Super-Linter
#         uses: github/super-linter@v4
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#           WORKSPACE: Backend-easyrent

#           VALIDATE_PHP: true
#           VALIDATE_JSON: true
#           VALIDATE_YAML: true

name: Exemple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      # Récupérer le code
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd frontend_easyrent
             npm install               # Installer les dépendances
      - run: npm test                   # Lancer les tests

  deploy:
    needs: build-and-test               # S’exécute seulement si build/test réussit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Déployer l’application
        run: echo "Ici tu mets ton script pour déployer sur ton serveur"